// Next/browser integration with a synthetic HTTP contract fixture, NOT real Odoo.
const {createServer}=require('node:http'),{spawn}=require('node:child_process'),assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
process.env.NO_PROXY='localhost,127.0.0.1';process.env.no_proxy=process.env.NO_PROXY;
const origin='http://localhost:3100',staffKey='synthetic-staff-pair-0000000000000000000';
let approved=false,prepares=0,approvals=0;
const session={sessionId:'11',title:'Synthetic afternoon class',startsAt:'2026-10-12T17:00:00Z',endsAt:'2026-10-12T18:00:00Z',capacity:10,seatsTaken:1,version:1};
const draft='Thank you for letting us know. Staff will review makeup options. No booking has changed.';
const fixture=createServer(async(req,res)=>{try{let raw='';for await(const b of req)raw+=b;const {operation,payload}=JSON.parse(raw).params;let result;
if(req.url.endsWith('/member'))result={member:{id:'22',tenantId:'test',memberNumber:'M22',name:'Synthetic Student',membershipState:'active',rank:{name:'Blue',stripes:0},attendanceRate:1},attendance:{latest:null,lastSevenDays:0}};
else if(req.url.endsWith('/members'))result={members:[{id:'22',name:'Synthetic Student'}]};
else if(operation==='context')result={sessions:[session],roster:[{memberId:'22',displayName:'Synthetic S.',enrollmentStatus:'registered',attendanceState:'pending'}],followUps:approved?[{id:'42',memberId:'22',sessionId:'11',memberName:'Synthetic Student',summary:'Parent attendance concern; review required.',replyDraft:draft,at:'2026-10-09T21:00:00Z',status:'Saved internally; not sent',mode:'Template draft - AI not enabled'}]:[],followUpEnabled:true,aiEnabled:false,sessionTitle:session.title};
else if(operation==='prepare'){prepares++;assert.equal(payload.memberId,'22');assert.equal(payload.sessionId,'11');result={outcome:'newTask',suggestion:{id:'followup:42',title:'Review parent follow-up',explanation:'Internal follow-up only.',actionLabel:'Approve internal follow-up',capability:'followup.save_internal',risk:'medium',preview:[{label:'Report',value:payload.text},{label:'Reply draft',value:draft},{label:'Mode',value:'Template draft - AI not enabled'}]}}}
else if(operation==='approve'){approved=true;approvals++;result={receipt:{id:'42',suggestionId:'followup:42',summary:'Saved internally. No message sent.',actor:'Staff test',at:'2026-10-09T21:00:00Z'},replayed:approvals>1,correlationId:payload.correlationId,evidence:{source:'odoo-test',memberId:'22'}}}
else result={outcome:'notUnderstood'};
res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({result}));}catch(e){console.error(e);res.writeHead(500);res.end()}});
const env={...process.env,DOJANG_INTEGRATION_MODE:'odoo-test',NEXT_PUBLIC_DEMO_MODE:'false',DOJANG_PUBLIC_ORIGIN:origin,DOJANG_ODOO_URL:'http://127.0.0.1:18069',DOJANG_KIOSK_TOKEN:'synthetic-token-000000000000',DOJANG_COOKIE_SECRET:'synthetic-cookie-secret-000000000000000',DOJANG_KIOSK_GATEWAY_KEY:'synthetic-kiosk-gateway-000000000000000',DOJANG_STAFF_GATEWAY_KEY:'synthetic-staff-gateway-000000000000000',DOJANG_KIOSK_PAIR_KEY:'synthetic-kiosk-pair-key-00000000000000',DOJANG_STAFF_PAIR_KEY:staffKey};
(async()=>{let app,browser;const errors=[],dir=process.env.DOJANG_EVIDENCE_DIR || '/tmp/dojang-companion-ui';fs.mkdirSync(dir,{recursive:true});try{
await new Promise(r=>fixture.listen(18069,'127.0.0.1',r));app=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3100'],{env,stdio:['ignore','pipe','pipe']});let logs='';const log=b=>{logs+=b;fs.writeFileSync(dir+'/server.log',logs)};app.stdout.on('data',log);app.stderr.on('data',log);
let ready=false;for(let i=0;i<20;i++){try{if((await fetch(origin+'/integration/pair',{signal:AbortSignal.timeout(1500)})).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,300))}if(!ready)throw Error('Next server unavailable: '+logs);
console.log('Starting browser');browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1500,height:1000}});page.on('pageerror',e=>errors.push(e.message));
console.log('Pairing');await page.goto(origin+'/integration/pair');await page.locator('select[name=role]').selectOption('staff');await page.locator('input[name=pairKey]').fill(staffKey);await page.getByRole('button',{name:'Connect test device'}).click();await page.waitForURL('**/integration/members');
console.log('Preparing follow-up');await page.goto(origin+'/people/22');await page.getByText('Prepare parent follow-up',{exact:true}).click();await page.getByLabel('Reported class').selectOption('11');await page.getByLabel('Parent report',{exact:true}).fill('My child cannot attend. Could we arrange a makeup?');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Prepare for review',exact:true}).click();await page.getByRole('button',{name:'Approve internal follow-up',exact:true}).waitFor();assert.equal(approved,false);await page.screenshot({path:dir+'/proposal.png',fullPage:true});
await page.getByRole('button',{name:'Approve internal follow-up',exact:true}).click();await page.getByText('Saved internally; not sent',{exact:false}).first().waitFor();assert.equal(approvals,1);assert.equal(prepares,1);
await page.goto(origin+'/ops/sessions/11');await page.getByRole('link',{name:'Synthetic S.',exact:true}).waitFor();await page.getByText('Saved internally; not sent',{exact:false}).waitFor();await page.getByRole('textbox',{name:'Ask the agent'}).fill('Who has not checked in?');await page.getByRole('button',{name:'Send',exact:true}).click();await page.getByText('Synthetic S.: Not yet checked in',{exact:true}).waitFor();await page.screenshot({path:dir+'/class-roster.png',fullPage:true});
await page.goto(origin+'/ops');await page.getByText('Saved internally; not sent',{exact:false}).waitFor();await page.setViewportSize({width:390,height:844});await page.goto(origin+'/people/22');await page.getByRole('button',{name:'Open companion',exact:true}).click();await page.getByText('Prepare parent follow-up',{exact:true}).waitFor({state:'visible'});await page.screenshot({path:dir+'/mobile.png',fullPage:true});
const guest=await browser.newContext();const denied=await guest.request.post(origin+'/api/v2/companion/requests',{headers:{origin},data:{memberId:'22',text:'show attendance',onScreenIds:[]}});assert.equal(denied.status(),403);await guest.close();assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/server.log',logs);console.log('PASS: browser/Next/HTTP fixture proposal, approval, member history, class and staff queue, mobile, unpaired rejection. No live Odoo or AI used.');
}finally{if(browser)await browser.close();if(app)app.kill();fixture.close()}})().catch(e=>{console.error(e);process.exitCode=1});
